<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Archetype.Core\Archetype.Core.csproj" />
    <ProjectReference Include="..\..\src\Archetype.Build\Archetype.Build.csproj" />
    <ProjectReference Include="..\..\src\Archetype.Text\Archetype.Text.csproj" />
    <ProjectReference Include="..\..\src\Archetype.Engine\Archetype.Engine.csproj" />
  </ItemGroup>

</Project>