using System.Text;
using Archetype.Core;

namespace Archetype.Tooling.Server.Export;

// ---------------------------------------------------------------------------
//  GodotClassGenerator — GDScript class generation for Godot export (D30)
// ---------------------------------------------------------------------------

/// <summary>
/// Generates the GDScript class files for the Godot export package (D30).
/// <para>
/// Signal derivation rules (D30 Level 1):
/// <list type="bullet">
/// <item>Include: keywords referenced directly in any card's primary/named effect, cost body, or static effect.</item>
/// <item>Suppress by default: all built-in primitives.</item>
/// <item>Override: <see cref="SignalBehaviour.ForceInclude"/> opts a primitive in; <see cref="SignalBehaviour.Suppress"/> opts a game-creator keyword out.</item>
/// </list>
/// </para>
/// </summary>
public static class GodotClassGenerator
{
    /// <summary>
    /// Generates all GDScript output files and returns a
    /// <c>filename → content</c> map.  The Electron main process writes
    /// these files to the configured output directory.
    /// </summary>
    public static IReadOnlyDictionary<string, string> Generate(ProjectState state)
    {
        var signalSet = DeriveSignalSet(state);

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["generated/ArchetypeCard.gd"]         = GenerateCardClass(state, signalSet),
            ["generated/ArchetypeZone.gd"]         = GenerateZoneClass(state, signalSet),
            ["generated/ArchetypePlayer.gd"]       = GeneratePlayerClass(state, signalSet),
            ["generated/ArchetypeSession.gd"]      = GenerateSessionClass(state, signalSet),
            ["generated/ArchetypeCardImporter.gd"] = GenerateCardImporter(),
            ["interop/ArchetypeInterop.gd"]        = GenerateInteropWrapper(),
        };
    }

    // -----------------------------------------------------------------------
    //  Signal set derivation (D30)
    // -----------------------------------------------------------------------

    /// <summary>
    /// Returns the set of keyword names that should generate GDScript signals,
    /// paired with their <see cref="KeywordDefinition"/> for type information.
    /// </summary>
    public static IReadOnlyList<SignalSpec> DeriveSignalSet(ProjectState state)
    {
        var builtInNames = new HashSet<string>(
            BuiltInKeywords.All.Select(k => k.Name),
            StringComparer.Ordinal);

        // Collect all keyword names referenced directly in card effects.
        var cardReferenced = new HashSet<string>(StringComparer.Ordinal);
        foreach (var card in state.Cards.Values)
            foreach (var r in ReferenceGraph.DirectRefsFromCard(card))
                cardReferenced.Add(r);

        var result = new List<SignalSpec>();

        foreach (var name in cardReferenced)
        {
            bool isBuiltIn = builtInNames.Contains(name);

            // Resolve signal behaviour override.
            SignalBehaviour behaviour = SignalBehaviour.Default;
            if (state.Keywords.TryGetValue(name, out var kwEntry))
                behaviour = kwEntry.SignalBehaviour;

            // Derivation rules:
            bool include = behaviour switch
            {
                SignalBehaviour.ForceInclude => true,
                SignalBehaviour.Suppress     => false,
                // Default: suppress built-ins, include game-creator keywords.
                _ => !isBuiltIn,
            };

            if (!include) continue;

            // Resolve parameter list for signal shape.
            List<ParameterDecl> parameters;
            if (kwEntry is not null)
                parameters = kwEntry.Parameters;
            else
            {
                var builtin = BuiltInKeywords.All.FirstOrDefault(k => k.Name == name);
                parameters = builtin?.Parameters.ToList() ?? [];
            }

            result.Add(new SignalSpec(name, parameters));
        }

        return result;
    }

    // -----------------------------------------------------------------------
    //  Class generators
    // -----------------------------------------------------------------------

    private static string GenerateCardClass(
        ProjectState state, IReadOnlyList<SignalSpec> signalSet)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ArchetypeCard.gd — generated by Archetype authoring tool; do not edit");
        sb.AppendLine("class_name ArchetypeCard extends RefCounted");
        sb.AppendLine();
        sb.AppendLine("## Atom ID identifying which engine card atom this instance represents.");
        sb.AppendLine("var atom_id: int");
        sb.AppendLine();

        // Static properties for cards (from project's CardDefinition schema)
        AppendStaticPropertyPlaceholder(sb, "Cards");

        // Signals (card-scoped keywords only)
        AppendSignals(sb, signalSet);

        return sb.ToString();
    }

    private static string GenerateZoneClass(
        ProjectState state, IReadOnlyList<SignalSpec> signalSet)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ArchetypeZone.gd — generated by Archetype authoring tool; do not edit");
        sb.AppendLine("class_name ArchetypeZone extends RefCounted");
        sb.AppendLine();
        sb.AppendLine("## Atom ID identifying which engine zone atom this instance represents.");
        sb.AppendLine("var atom_id: int");
        sb.AppendLine();
        AppendStaticPropertyPlaceholder(sb, "Zones");
        AppendSignals(sb, signalSet);
        return sb.ToString();
    }

    private static string GeneratePlayerClass(
        ProjectState state, IReadOnlyList<SignalSpec> signalSet)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ArchetypePlayer.gd — generated by Archetype authoring tool; do not edit");
        sb.AppendLine("class_name ArchetypePlayer extends RefCounted");
        sb.AppendLine();
        sb.AppendLine("## Atom ID identifying which engine player atom this instance represents.");
        sb.AppendLine("var atom_id: int");
        sb.AppendLine();
        AppendStaticPropertyPlaceholder(sb, "Players");
        AppendSignals(sb, signalSet);
        return sb.ToString();
    }

    private static string GenerateSessionClass(
        ProjectState state, IReadOnlyList<SignalSpec> signalSet)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ArchetypeSession.gd — generated by Archetype authoring tool; do not edit");
        sb.AppendLine("class_name ArchetypeSession extends RefCounted");
        sb.AppendLine();
        sb.AppendLine("## Atom ID identifying the engine session atom.");
        sb.AppendLine("var atom_id: int");
        sb.AppendLine();
        AppendSignals(sb, signalSet);
        return sb.ToString();
    }

    private static string GenerateCardImporter()
    {
        // ArchetypeCardImporter.gd — standard template; game-creator runs this
        // once after GameSession is built to populate the atom registry.
        return """
# ArchetypeCardImporter.gd — generated by Archetype authoring tool; do not edit
# Responsibilities:
#   1. Loads game-definition.json and wires the C# GameSession via ArchetypeInterop.gd.
#   2. After GameSession is built, creates ArchetypeCard instances for each card atom.
#   3. Loads art/<card-name>.png and attaches it as a Texture2D property.
#   4. Returns the populated registry Dictionary[int, ArchetypeCard].
class_name ArchetypeCardImporter extends RefCounted

## Set up the card registry for the given session.
## Returns a Dictionary mapping AtomId (int) -> ArchetypeCard instance.
static func setup(session, output_dir: String) -> Dictionary:
	var registry: Dictionary = {}
	var state_view = ArchetypeInterop.get_state_view(session)
	var card_atoms = ArchetypeInterop.get_atoms(state_view, "card")
	for atom_id in card_atoms:
		var card = ArchetypeCard.new()
		card.atom_id = atom_id
		var def_name = ArchetypeInterop.get_definition_name(state_view, atom_id)
		var art_path = output_dir.path_join("art").path_join(def_name + ".png")
		if ResourceLoader.exists(art_path):
			card.set_meta("texture", load(art_path))
		registry[atom_id] = card
	return registry
""";
    }

    private static string GenerateInteropWrapper()
    {
        // ArchetypeInterop.gd — one-time C#->GDScript wrapper.
        // Generated once; regenerated only on explicit "Regenerate Interop" action.
        return """
# ArchetypeInterop.gd — generated by Archetype authoring tool
# Wraps the Archetype C# engine API surface for GDScript access.
# Regenerate this file only after an engine update.
class_name ArchetypeInterop extends RefCounted

## Creates a new GameSession for the given game definition JSON.
static func create_session(definition_json: String):
	return Archetype.Engine.GameSession.CreateFromJson(definition_json)

## Returns the GameStateView for the session.
static func get_state_view(session):
	return session.StateView

## Returns all atom IDs of the given kind ("card", "zone", "player").
static func get_atoms(state_view, kind: String) -> Array:
	return state_view.GetAtomIds(kind)

## Returns the definition name for an atom.
static func get_definition_name(state_view, atom_id: int) -> String:
	return state_view.GetDefinitionName(atom_id)

## Returns the LastActionEvents from the most recently completed action.
static func get_last_action_events(state_view) -> Array:
	return state_view.LastActionEvents

## Emits signals on ArchetypeCard/Zone/Player instances based on LastActionEvents.
## Call this after each awaited action.
static func deliver_signals(state_view, registry: Dictionary) -> void:
	var events = get_last_action_events(state_view)
	for ev in events:
		var atom_arg = ev.GetAtomArg()
		if atom_arg in registry:
			var instance = registry[atom_arg]
			# Signal name: on_<keyword_name_with_underscores>
			var signal_name = "on_" + ev.KeywordName.replace("-", "_")
			if instance.has_signal(signal_name):
				instance.emit_signal(signal_name)
""";
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    private static void AppendStaticPropertyPlaceholder(
        StringBuilder sb, string entityKind)
    {
        sb.AppendLine($"# Static properties (from game's {entityKind} schema)");
        sb.AppendLine("# Add your schema-specific properties below:");
        sb.AppendLine();
    }

    private static void AppendSignals(
        StringBuilder sb, IReadOnlyList<SignalSpec> signalSet)
    {
        if (signalSet.Count == 0) return;
        sb.AppendLine("# Signals derived from keyword usage in card effect blocks (D30)");
        foreach (var sig in signalSet)
        {
            var gdParams = sig.Parameters
                .Select(p => $"{p.Name}: {MapTypeToGdScript(p.Type)}")
                .ToList();
            sb.AppendLine($"signal on_{sig.GdScriptName}({string.Join(", ", gdParams)})");
        }
        sb.AppendLine();
    }

    /// <summary>Maps a <see cref="TypeName"/> to a GDScript type annotation (D30).</summary>
    private static string MapTypeToGdScript(TypeName t) => t switch
    {
        TypeName.Number        => "float",
        TypeName.Boolean       => "bool",
        TypeName.Atom          => "int",
        TypeName.Card          => "int",
        TypeName.Zone          => "int",
        TypeName.Player        => "int",
        TypeName.Session       => "int",
        TypeName.ContributionId => "int",
        _                      => "String",
    };
}

// ---------------------------------------------------------------------------
//  SignalSpec — one derived signal
// ---------------------------------------------------------------------------

/// <summary>A keyword that will produce a GDScript signal in the export.</summary>
public sealed record SignalSpec(
    string Name,
    IReadOnlyList<ParameterDecl> Parameters)
{
    /// <summary>GDScript signal name: hyphens converted to underscores.</summary>
    public string GdScriptName => Name.Replace('-', '_');
}
