using System.Text;
using Archetype.Core;

namespace Archetype.Build;

/// <summary>
/// Generates GDScript interop files from a <see cref="GameDefinition"/> (D32).
/// <para>
/// Two files are produced:
/// <list type="bullet">
///   <item><c>archetype_keywords.gd</c> — SCREAMING_SNAKE_CASE string constants for every registered keyword name.</item>
///   <item><c>game_events.gd</c> — GDScript signal declarations derived from keyword event log contributions.</item>
/// </list>
/// </para>
/// </summary>
public static class GodotEmitter
{
    // -----------------------------------------------------------------------
    //  Keyword constants file
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>archetype_keywords.gd</c> to <paramref name="outputDir"/>.
    /// Contains one SCREAMING_SNAKE_CASE string constant per registered keyword name.
    /// </summary>
    public static void EmitKeywordConstants(GameDefinition definition, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_keywords.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("class_name ArchetypeKeywords");
        sb.AppendLine();

        foreach (var name in definition.Keywords.Keys.OrderBy(k => k))
        {
            var constName = ToScreamingSnakeCase(name);
            sb.AppendLine($"const {constName} = \"{name}\"");
        }

        File.WriteAllText(Path.Combine(outputDir, "archetype_keywords.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  Signal definitions file
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>game_events.gd</c> to <paramref name="outputDir"/>.
    /// <para>
    /// Signal derivation rules (D32 / D30):
    /// <list type="bullet">
    ///   <item>A keyword produces a signal if it is directly referenced as an
    ///         <c>EffectBlockStep</c> in any card's primary effect, additional
    ///         effect bodies, or cost bodies.</item>
    ///   <item>Built-in primitives are suppressed by default.</item>
    ///   <item>Keywords in <paramref name="noSignalKeywords"/> are excluded.</item>
    /// </list>
    /// </para>
    /// </summary>
    public static void EmitSignals(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var suppressed = noSignalKeywords?.ToHashSet() ?? [];
        var builtInNames = BuiltInKeywords.All.Select(k => k.Name).ToHashSet();

        // Collect keyword names directly referenced in card effect blocks.
        var referenced = new HashSet<string>();
        foreach (var card in definition.CardDefinitions.Values)
        {
            CollectFromBlock(card.PrimaryEffect, referenced);
            foreach (var extra in card.AdditionalEffects)
                CollectFromBlock(extra.Body, referenced);
            foreach (var cost in card.Cost ?? [])
                CollectFromBlock(cost.Body, referenced);
        }

        // Apply derivation rules: exclude built-ins and opted-out keywords.
        var included = referenced
            .Where(name => !builtInNames.Contains(name))
            .Where(name => !suppressed.Contains(name))
            .OrderBy(name => name)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# game_events.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("class_name GameEvents");
        sb.AppendLine();

        if (included.Count == 0)
        {
            sb.AppendLine("# No game-creator keyword signals derived from card definitions.");
        }
        else
        {
            foreach (var name in included)
            {
                if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
                var signalName = "on_" + name.Replace('-', '_');
                var paramList = string.Join(", ", kw.Parameters.Select(p =>
                    $"{p.Name}: {MapToGdScriptType(p.Type)}"));
                sb.AppendLine($"signal {signalName}({paramList})");
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "game_events.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    private static void CollectFromBlock(EffectBlockDef block, HashSet<string> collected)
    {
        foreach (var step in block.Steps)
            collected.Add(step.KeywordName);
    }

    /// <summary>
    /// Converts a kebab-case keyword name to SCREAMING_SNAKE_CASE.
    /// <example><c>take-damage</c> → <c>TAKE_DAMAGE</c></example>
    /// </summary>
    internal static string ToScreamingSnakeCase(string name) =>
        name.Replace('-', '_').ToUpperInvariant();

    /// <summary>Maps an engine <see cref="TypeName"/> to a GDScript type annotation.</summary>
    internal static string MapToGdScriptType(TypeName type) => type switch
    {
        TypeName.Number                                           => "float",
        TypeName.Boolean                                          => "bool",
        TypeName.Atom or TypeName.Card or TypeName.Zone
            or TypeName.Player or TypeName.Session
            or TypeName.ContributionId                            => "int",
        TypeName.ConditionName or TypeName.PropertyName           => "String",
        TypeName.CardDefinitionName or TypeName.ZoneDefinitionName => "String",
        _                                                         => "Variant",
    };
}
