using System.Text;
using Archetype.Core;

namespace Archetype.Build;

/// <summary>
/// Generates GDScript interop files from a <see cref="GameDefinition"/> (D32, D33, D38, D39).
/// <para>
/// Files produced:
/// <list type="bullet">
///   <item><c>archetype_keywords.gd</c> — SCREAMING_SNAKE_CASE string constants for every registered keyword name.</item>
///   <item><c>game_events.gd</c> — GDScript signal declarations derived from keyword event log contributions.</item>
///   <item><c>ArchetypeNode.cs</c> — generated C# partial class bridging <c>GameSession</c> to GDScript (D33).</item>
///   <item><c>archetype_signals.gd</c> — per-game signal name constants in SCREAMING_SNAKE_CASE (D33).</item>
///   <item><c>archetype_interop.gd</c> — static autoload wrapper over <c>ArchetypeNode</c> with state query forwarding methods (D33, D38).</item>
///   <item><c>archetype_atom_kinds.gd</c> — integer constants for <see cref="AtomKind"/> values (D39).</item>
/// </list>
/// </para>
/// </summary>
public static class GodotEmitter
{
    // -----------------------------------------------------------------------
    //  Keyword constants file
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>archetype_keywords.gd</c> to <paramref name="outputDir"/>.
    /// Contains one SCREAMING_SNAKE_CASE string constant per registered keyword name.
    /// </summary>
    public static void EmitKeywordConstants(GameDefinition definition, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_keywords.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("## String constants for every registered keyword name.");
        sb.AppendLine("##");
        sb.AppendLine("## Use these instead of bare strings to avoid typos when referencing");
        sb.AppendLine("## keywords in code.");
        sb.AppendLine("class_name ArchetypeKeywords");
        sb.AppendLine();

        foreach (var name in definition.Keywords.Keys.OrderBy(k => k))
        {
            var constName = ToScreamingSnakeCase(name);
            sb.AppendLine($"## Keyword identifier for [b]{name}[/b].");
            sb.AppendLine($"const {constName} = \"{name}\"");
        }

        File.WriteAllText(Path.Combine(outputDir, "archetype_keywords.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  Signal definitions file
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>game_events.gd</c> to <paramref name="outputDir"/>.
    /// <para>
    /// Signal derivation rules (D32 / D30):
    /// <list type="bullet">
    ///   <item>A keyword produces a signal if it is directly referenced as an
    ///         <c>EffectBlockStep</c> in any card's primary effect, additional
    ///         effect bodies, or cost bodies.</item>
    ///   <item>Built-in primitives are suppressed by default.</item>
    ///   <item>Keywords in <paramref name="noSignalKeywords"/> are excluded.</item>
    /// </list>
    /// </para>
    /// </summary>
    public static void EmitSignals(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var included = DeriveSignalSet(definition, noSignalKeywords);

        var sb = new StringBuilder();
        sb.AppendLine("# game_events.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("## Typed signal declarations for every keyword referenced in card definitions.");
        sb.AppendLine("##");
        sb.AppendLine("## Connect to these on [ArchetypeNode] to react to specific game events.");
        sb.AppendLine("class_name GameEvents");
        sb.AppendLine();

        if (included.Count == 0)
        {
            sb.AppendLine("# No game-creator keyword signals derived from card definitions.");
        }
        else
        {
            foreach (var name in included)
            {
                if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
                var signalName = "on_" + name.Replace('-', '_');
                var paramList = string.Join(", ", kw.Parameters.Select(p =>
                    $"{p.Name}: {MapToGdScriptType(p.Type)}"));
                sb.AppendLine($"## Emitted when the [b]{name}[/b] keyword resolves.");
                foreach (var p in kw.Parameters)
                    sb.AppendLine($"## [param {p.Name}]: {GdScriptParamDescription(p.Name, p.Type)}");
                sb.AppendLine($"signal {signalName}({paramList})");
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "game_events.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  ArchetypeNode.cs — C# bridge class (D33)
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>ArchetypeNode.cs</c> to <paramref name="outputDir"/> (D33).
    /// <para>
    /// The generated class is a Godot <c>Node</c> partial that wraps
    /// <c>GameSession</c>, implements <c>IPlayerStrategy</c> internally for
    /// every player, and bridges the async action loop to GDScript via
    /// <c>TaskCompletionSource</c>-based suspension.  All Godot coupling is
    /// confined to the generated string — the <c>Archetype.*</c> assemblies
    /// gain no Godot reference.
    /// </para>
    /// </summary>
    public static void EmitArchetypeNode(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var signalSet = DeriveSignalSet(definition, noSignalKeywords);
        var playerNames = definition.PlayerDefinitions.Keys.OrderBy(n => n).ToList();

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// ArchetypeNode.cs — generated by Archetype.Build; do not edit");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Godot;");
        sb.AppendLine("using Archetype.Build;");
        sb.AppendLine("using Archetype.Core;");
        sb.AppendLine("using Archetype.Engine;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated Godot node that hosts a <c>GameSession</c> and bridges the async");
        sb.AppendLine("/// action loop to GDScript via signal/method pairs (D33).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[GlobalClass]");
        sb.AppendLine("public partial class ArchetypeNode : Node");
        sb.AppendLine("{");

        // --- Signal declarations ---
        sb.AppendLine("    // --- Engine lifecycle signals ---");
        sb.AppendLine("    [Signal] public delegate void ActionRequestedEventHandler(string playerName, Godot.Collections.Dictionary availableActions);");
        sb.AppendLine("    [Signal] public delegate void ActionResolvedEventHandler();");
        sb.AppendLine("    [Signal] public delegate void PromptRequestedEventHandler(string playerName, string promptType, Godot.Collections.Dictionary context);");
        sb.AppendLine("    [Signal] public delegate void GameOverEventHandler(string winnerName);");
        sb.AppendLine("    [Signal] public delegate void GameErrorEventHandler(string message);");
        sb.AppendLine();

        if (signalSet.Count > 0)
        {
            sb.AppendLine("    // --- Derived keyword signals ---");
            foreach (var name in signalSet)
            {
                if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
                var handlerName = "On" + ToPascalCase(name) + "EventHandler";
                var paramList = string.Join(", ", kw.Parameters.Select(p =>
                    $"{MapToCSharpType(p.Type)} {p.Name}"));
                sb.AppendLine($"    [Signal] public delegate void {handlerName}({paramList});");
            }
            sb.AppendLine();
        }

        // --- Session fields ---
        sb.AppendLine("    // --- Session state ---");
        sb.AppendLine("    private Task? _runTask;");
        sb.AppendLine("    private CancellationTokenSource? _cts;");
        // _stateView is set by InnerStrategy before each action/prompt window (D38).
        // Query methods return safe defaults when it is null (before game start or after game over).
        sb.AppendLine("    private GameStateView? _stateView;");
        sb.AppendLine();

        // One TCS pair per player for action + prompt suspension.
        // We use runtime dictionaries keyed by player name so the same node
        // handles games with any number of players.
        sb.AppendLine("    // Per-player suspension: one TCS per outstanding SelectAction / RespondToPrompt call.");
        sb.AppendLine("    private readonly Dictionary<string, TaskCompletionSource<PlayerAction?>> _pendingActions = new();");
        sb.AppendLine("    private readonly Dictionary<string, TaskCompletionSource<PromptResponse>> _pendingPrompts = new();");
        sb.AppendLine();

        // --- StartGame ---
        sb.AppendLine("    // --- Session startup ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Loads the game definition and card sets from the generated JSON files,");
        sb.AppendLine("    /// then starts the game session.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"hostManifestData\">Session-specific overrides; pass an empty");
        sb.AppendLine("    /// <c>Dictionary</c> if none are needed.</param>");
        sb.AppendLine("    /// <param name=\"definitionPath\">Resource path to <c>game_definition.json</c>.</param>");
        sb.AppendLine("    /// <param name=\"cardSetPaths\">Array of resource paths to card-set JSON files.</param>");
        sb.AppendLine("    public void StartGame(");
        sb.AppendLine("        Godot.Collections.Dictionary hostManifestData,");
        sb.AppendLine("        string definitionPath = \"res://archetype/game_definition.json\",");
        sb.AppendLine("        Godot.Collections.Array? cardSetPaths = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var jsonOptions = GameDefinitionJsonOptions.Build();");
        sb.AppendLine("        var defJson = FileAccess.GetFileAsString(definitionPath);");
        sb.AppendLine("        var definition = JsonSerializer.Deserialize<GameDefinition>(defJson, jsonOptions)!;");
        sb.AppendLine();
        sb.AppendLine("        var cardSets = new List<CardSet>();");
        sb.AppendLine("        var paths = (cardSetPaths == null || cardSetPaths.Count == 0) ? LoadDefaultCardSetPaths() : cardSetPaths;");
        sb.AppendLine("        foreach (var path in paths)");
        sb.AppendLine("        {");
        sb.AppendLine("            var json = FileAccess.GetFileAsString(path.ToString()!);");
        sb.AppendLine("            var set = JsonSerializer.Deserialize<CardSet>(json, jsonOptions);");
        sb.AppendLine("            if (set != null) cardSets.Add(set);");
        sb.AppendLine("        }");
        sb.AppendLine("        definition = definition.WithCardSets(cardSets);");
        sb.AppendLine();
        sb.AppendLine("        _cts = new CancellationTokenSource();");
        sb.AppendLine("        var builder = GameSession.Create(definition)");
        sb.AppendLine("            .WithRandomSource(new Archetype.Engine.SeededRandom(GD.Randi()));");
        sb.AppendLine();

        foreach (var playerName in playerNames)
        {
            sb.AppendLine($"        builder = builder.WithPlayerStrategy(\"{playerName}\", new InnerStrategy(\"{playerName}\", this));");
        }

        sb.AppendLine();
        sb.AppendLine("        var session = builder.Build();");
        sb.AppendLine("        _runTask = RunLoopAsync(session, _cts.Token);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static Godot.Collections.Array LoadDefaultCardSetPaths()");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new Godot.Collections.Array();");
        sb.AppendLine("        var dir = DirAccess.Open(\"res://archetype/card-sets/\");");
        sb.AppendLine("        if (dir == null) return result;");
        sb.AppendLine("        foreach (var file in dir.GetFiles())");
        sb.AppendLine("            if (file.EndsWith(\".json\"))");
        sb.AppendLine("                result.Add($\"res://archetype/card-sets/{file}\");");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- RunLoopAsync ---
        sb.AppendLine("    private async Task RunLoopAsync(GameSession session, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = await session.RunAsync(ct);");
        sb.AppendLine("            // winnerName is empty string for a draw (D33 spec).");
        sb.AppendLine("            EmitSignal(SignalName.GameOver, result.Winner ?? string.Empty);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.OperationCanceledException)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Normal shutdown: node exited tree while game was running.");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            GD.PrintErr(\"[ArchetypeNode] engine error: \", ex.Message, \"\\n\", ex.StackTrace);");
        sb.AppendLine("            EmitSignal(SignalName.GameError, ex.Message);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- _ExitTree ---
        sb.AppendLine("    /// <summary>Cancels the game loop when the node leaves the scene tree.</summary>");
        sb.AppendLine("    public override void _ExitTree()");
        sb.AppendLine("    {");
        sb.AppendLine("        _cts?.Cancel();");
        sb.AppendLine("        _cts?.Dispose();");
        sb.AppendLine("        _cts = null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- Action submission methods ---
        sb.AppendLine("    // --- GDScript-callable action submission methods ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits a play-card action for the named player.</summary>");
        sb.AppendLine("    public void SubmitPlayCard(string playerName, long cardAtomId, Godot.Collections.Dictionary costChoices)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        var choices = DictionaryToStringObject(costChoices);");
        sb.AppendLine("        tcs.TrySetResult(new PlayCard(new AtomId(cardAtomId), choices));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits an activate-ability action for the named player.</summary>");
        sb.AppendLine("    public void SubmitActivateAbility(string playerName, long sourceAtomId, string effectName, Godot.Collections.Dictionary costChoices)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        var choices = DictionaryToStringObject(costChoices);");
        sb.AppendLine("        tcs.TrySetResult(new ActivateAbility(new AtomId(sourceAtomId), effectName, choices));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits a pass action for the named player.</summary>");
        sb.AppendLine("    public void SubmitPass(string playerName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        tcs.TrySetResult(new Pass());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits a prompt response for the named player.</summary>");
        sb.AppendLine("    public void SubmitPromptResponse(string playerName, Godot.Collections.Dictionary response)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingPrompts.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        var chosen = new System.Collections.Generic.List<object>();");
        sb.AppendLine("        foreach (var key in response.Keys)");
        sb.AppendLine("            chosen.Add(response[key]);");
        sb.AppendLine("        tcs.TrySetResult(new ChoiceResponse(chosen));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- EmitDerivedSignals ---
        sb.AppendLine("    // --- Post-action signal emission ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Iterates <paramref name=\"events\"/> (depth-first) and emits a hardcoded");
        sb.AppendLine("    /// GDScript signal for every event whose keyword name is in the derived set.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private void EmitDerivedSignals(System.Collections.Generic.IReadOnlyList<GameEvent> events)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var root in events)");
        sb.AppendLine("        foreach (var ev in root.SelfAndDescendants())");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (ev.KeywordName)");
        sb.AppendLine("            {");

        foreach (var name in signalSet)
        {
            if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
            var signalConstant = "SignalName.On" + ToPascalCase(name);
            sb.AppendLine($"                case \"{name}\":");
            sb.AppendLine($"                    EmitSignal({signalConstant}");

            foreach (var p in kw.Parameters)
            {
                var cast = GetEventArgCast(p.Type);
                sb.AppendLine($"                        , {cast}(ev.BoundArgs[\"{p.Name}\"])");
            }

            sb.AppendLine("                    );");
            sb.AppendLine("                    break;");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- DictionaryToStringObject helper ---
        sb.AppendLine("    private static System.Collections.Generic.Dictionary<string, object> DictionaryToStringObject(");
        sb.AppendLine("        Godot.Collections.Dictionary dict)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new System.Collections.Generic.Dictionary<string, object>(StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var key in dict.Keys)");
        sb.AppendLine("            result[key.ToString()!] = dict[key];");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- State query methods (D38) ---
        // These forward to _stateView and return safe defaults when null (before game start or after game over).
        sb.AppendLine("    // --- GDScript-callable state query methods (D38) ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the named accumulator value for the given atom, or 0.0 if no state is available.</summary>");
        sb.AppendLine("    public double GetAccumulator(long atomId, string name) => _stateView?.GetAccumulator(new AtomId(atomId), name) ?? 0.0;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns whether the named condition is set on the given atom, or false if no state is available.</summary>");
        sb.AppendLine("    public bool HasCondition(long atomId, string name) => _stateView?.HasCondition(new AtomId(atomId), name) ?? false;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the named computed property for the given atom, or 0.0 if no state is available.</summary>");
        sb.AppendLine("    public double GetComputedProperty(long atomId, string name) => _stateView?.GetComputedProperty(new AtomId(atomId), name) ?? 0.0;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the zone atom ID for the given card atom, or 0L if no state is available.</summary>");
        sb.AppendLine("    public long GetZone(long atomId) => _stateView != null ? (long)_stateView.GetZone(new AtomId(atomId)) : 0L;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the owner atom ID for the given atom, or 0L if no state is available.</summary>");
        sb.AppendLine("    public long GetAtomOwner(long atomId) => _stateView != null ? (long)_stateView.GetOwner(new AtomId(atomId)) : 0L;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the AtomKind ordinal for the given atom, or -1 if no state is available.</summary>");
        sb.AppendLine("    public int GetKind(long atomId) => _stateView != null ? (int)_stateView.GetKind(new AtomId(atomId)) : -1;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns all atom IDs of the given AtomKind as an array of longs.</summary>");
        sb.AppendLine("    public Godot.Collections.Array GetAtoms(int kind)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new Godot.Collections.Array();");
        sb.AppendLine("        if (_stateView == null) return result;");
        sb.AppendLine("        foreach (var id in _stateView.GetAtoms((AtomKind)kind))");
        sb.AppendLine("            result.Add((long)id);");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- InnerStrategy nested class ---
        sb.AppendLine("    // --- InnerStrategy — per-player IPlayerStrategy implementation ---");
        sb.AppendLine();
        sb.AppendLine("    private sealed class InnerStrategy : IPlayerStrategy");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly string _playerName;");
        sb.AppendLine("        private readonly ArchetypeNode _node;");
        sb.AppendLine();
        sb.AppendLine("        public InnerStrategy(string playerName, ArchetypeNode node)");
        sb.AppendLine("        {");
        sb.AppendLine("            _playerName = playerName;");
        sb.AppendLine("            _node = node;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task<PlayerAction?> SelectActionAsync(");
        sb.AppendLine("            AvailableActions available,");
        sb.AppendLine("            GameStateView state,");
        sb.AppendLine("            CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Emit derived signals for the just-completed action before opening");
        sb.AppendLine("            // the next decision window.  LastActionEvents is populated by the");
        sb.AppendLine("            // engine after all blocks, SBRs, and triggers resolve (D30).");
        sb.AppendLine("            _node.EmitDerivedSignals(state.LastActionEvents);");
        sb.AppendLine("            _node.EmitSignal(SignalName.ActionResolved);");
        sb.AppendLine();
        sb.AppendLine("            // Serialise available actions to a plain Dictionary for GDScript.");
        sb.AppendLine("            var availableDict = SerialiseAvailableActions(available);");
        sb.AppendLine("            var tcs = new TaskCompletionSource<PlayerAction?>(");
        sb.AppendLine("                TaskCreationOptions.RunContinuationsAsynchronously);");
        sb.AppendLine("            _node._pendingActions[_playerName] = tcs;");
        // Store state before emitting so query methods are callable during the action window (D38).
        sb.AppendLine("            _node._stateView = state;");
        sb.AppendLine("            _node.EmitSignal(SignalName.ActionRequested, _playerName, availableDict);");
        sb.AppendLine();
        sb.AppendLine("            using var reg = ct.Register(() => tcs.TrySetCanceled());");
        sb.AppendLine("            return await tcs.Task;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task<PromptResponse> RespondToPromptAsync(");
        sb.AppendLine("            PromptContext context,");
        sb.AppendLine("            GameStateView state,");
        sb.AppendLine("            CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            var promptType = context.GetType().Name;");
        sb.AppendLine("            var contextDict = new Godot.Collections.Dictionary();");
        sb.AppendLine("            var tcs = new TaskCompletionSource<PromptResponse>(");
        sb.AppendLine("                TaskCreationOptions.RunContinuationsAsynchronously);");
        sb.AppendLine("            _node._pendingPrompts[_playerName] = tcs;");
        // Store state before emitting so query methods are callable during the prompt window (D38).
        sb.AppendLine("            _node._stateView = state;");
        sb.AppendLine("            _node.EmitSignal(SignalName.PromptRequested, _playerName, promptType, contextDict);");
        sb.AppendLine();
        sb.AppendLine("            using var reg = ct.Register(() => tcs.TrySetCanceled());");
        sb.AppendLine("            return await tcs.Task;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static Godot.Collections.Dictionary SerialiseAvailableActions(AvailableActions available)");
        sb.AppendLine("        {");
        sb.AppendLine("            var dict = new Godot.Collections.Dictionary();");
        sb.AppendLine("            var cards = new Godot.Collections.Array();");
        sb.AppendLine("            foreach (var opt in available.PlayableCards)");
        sb.AppendLine("                cards.Add((long)opt.Card);");
        sb.AppendLine("            dict[\"playable_cards\"] = cards;");
        sb.AppendLine("            var abilities = new Godot.Collections.Array();");
        sb.AppendLine("            foreach (var opt in available.ActivatableAbilities)");
        sb.AppendLine("            {");
        sb.AppendLine("                var entry = new Godot.Collections.Dictionary();");
        sb.AppendLine("                entry[\"source\"] = (long)opt.Source;");
        sb.AppendLine("                entry[\"effect_name\"] = opt.EffectName;");
        sb.AppendLine("                abilities.Add(entry);");
        sb.AppendLine("            }");
        sb.AppendLine("            dict[\"activatable_abilities\"] = abilities;");
        sb.AppendLine("            dict[\"can_pass\"] = available.CanPass;");
        sb.AppendLine("            return dict;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("}");

        File.WriteAllText(Path.Combine(outputDir, "ArchetypeNode.cs"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  GDScript interop files (D33)
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>archetype_signals.gd</c> and <c>archetype_interop.gd</c> to
    /// <paramref name="outputDir"/> (D33).
    /// <para>
    /// <c>archetype_signals.gd</c> contains one SCREAMING_SNAKE_CASE constant
    /// per derived signal name, parallel to <c>archetype_keywords.gd</c>.
    /// </para>
    /// <para>
    /// <c>archetype_interop.gd</c> is a static autoload that re-emits
    /// <c>ArchetypeNode</c> signals so GDScript scripts can connect to a single
    /// stable node rather than to a scene-position-dependent node reference.
    /// Its content does not vary per game.
    /// </para>
    /// </summary>
    public static void EmitInteropScripts(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var signalSet = DeriveSignalSet(definition, noSignalKeywords);
        EmitSignalConstants(signalSet, outputDir);
        EmitInteropAutoload(outputDir);
    }

    // -----------------------------------------------------------------------
    //  Private helpers
    // -----------------------------------------------------------------------

    /// <summary>
    /// Derives the ordered set of keyword names for which GDScript signals
    /// should be generated.  Shared by <see cref="EmitSignals"/>,
    /// <see cref="EmitArchetypeNode"/>, and <see cref="EmitInteropScripts"/>.
    /// <para>
    /// Derivation rules (D30 / D32):
    /// keywords referenced directly in card effect steps, excluding built-in
    /// primitives and any name in <paramref name="noSignalKeywords"/>.
    /// </para>
    /// </summary>
    private static List<string> DeriveSignalSet(
        GameDefinition definition,
        IEnumerable<string>? noSignalKeywords)
    {
        var suppressed = noSignalKeywords?.ToHashSet() ?? [];
        var builtInNames = BuiltInKeywords.All.Select(k => k.Name).ToHashSet();

        // Collect keyword names directly referenced in card effect blocks.
        var referenced = new HashSet<string>();
        foreach (var card in definition.CardDefinitions.Values)
        {
            CollectFromBlock(card.PrimaryEffect, referenced);
            foreach (var extra in card.AdditionalEffects)
                CollectFromBlock(extra.Body, referenced);
            foreach (var cost in card.Cost ?? [])
                CollectFromBlock(cost.Body, referenced);
            // D32: also scan static effect blocks — both the state-contribution
            // block and the trigger's fired block count as referenced.
            foreach (var se in card.StaticEffects)
            {
                if (se.StateContributionBlock is not null)
                    CollectFromBlock(se.StateContributionBlock, referenced);
                if (se.Trigger is not null)
                    CollectFromBlock(se.Trigger.FiredBlock, referenced);
            }
        }

        // Apply derivation rules: exclude built-ins and opted-out keywords.
        return referenced
            .Where(name => !builtInNames.Contains(name))
            .Where(name => !suppressed.Contains(name))
            .OrderBy(name => name)
            .ToList();
    }

    /// <summary>Emits <c>archetype_signals.gd</c> from a pre-computed signal set.</summary>
    private static void EmitSignalConstants(List<string> signalSet, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_signals.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("## SCREAMING_SNAKE_CASE signal name constants for derived keyword signals.");
        sb.AppendLine("##");
        sb.AppendLine("## Use with [method Object.connect] as an alternative to bare strings.");
        sb.AppendLine("class_name ArchetypeSignals");
        sb.AppendLine();

        if (signalSet.Count == 0)
        {
            sb.AppendLine("# No game-creator keyword signals derived from card definitions.");
        }
        else
        {
            foreach (var name in signalSet)
            {
                var signalName = "on_" + name.Replace('-', '_');
                var constName = ToScreamingSnakeCase(signalName);
                sb.AppendLine($"## Signal name constant for [b]{signalName}[/b]. See [GameEvents].");
                sb.AppendLine($"const {constName} = \"{signalName}\"");
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "archetype_signals.gd"), sb.ToString());
    }

    /// <summary>
    /// Emits the game-agnostic <c>archetype_interop.gd</c> autoload.
    /// Content is fixed — it does not reference any derived signals.
    /// </summary>
    private static void EmitInteropAutoload(string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_interop.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("# Add to Project Settings > Autoload as \"ArchetypeInterop\"");
        sb.AppendLine("## Autoload bridge between [ArchetypeNode] and the rest of the scene tree.");
        sb.AppendLine("##");
        sb.AppendLine("## Register the [ArchetypeNode] instance via [method register] in your main");
        sb.AppendLine("## scene's [method Node._ready]. All other scripts connect to this autoload");
        sb.AppendLine("## rather than directly to the node, decoupling UI code from scene structure.");
        sb.AppendLine("##");
        sb.AppendLine("## [codeblock lang=gdscript]");
        sb.AppendLine("## func _ready() -> void:");
        sb.AppendLine("##     ArchetypeInterop.register($ArchetypeNode)");
        sb.AppendLine("##     ArchetypeInterop.action_requested.connect(_on_action_requested)");
        sb.AppendLine("## [/codeblock]");
        sb.AppendLine("extends Node");
        sb.AppendLine();
        sb.AppendLine("var _node: ArchetypeNode");
        sb.AppendLine();
        sb.AppendLine("## Registers [param node] and connects its lifecycle signals.");
        sb.AppendLine("## Call this from your main scene's [method Node._ready], then call [method start].");
        sb.AppendLine("func register(node: ArchetypeNode) -> void:");
        sb.AppendLine("    _node = node");
        sb.AppendLine("    _node.ActionRequested.connect(_on_action_requested)");
        sb.AppendLine("    _node.ActionResolved.connect(_on_action_resolved)");
        sb.AppendLine("    _node.PromptRequested.connect(_on_prompt_requested)");
        sb.AppendLine("    _node.GameOver.connect(_on_game_over)");
        sb.AppendLine("    _node.GameError.connect(_on_game_error)");
        sb.AppendLine();
        sb.AppendLine("## Emitted when a player must choose an action.");
        sb.AppendLine("## [param player_name] identifies which player is acting.");
        sb.AppendLine("## [param available] contains keys: [code]playable_cards[/code],");
        sb.AppendLine("## [code]activatable_abilities[/code], and [code]can_pass[/code].");
        sb.AppendLine("signal action_requested(player_name: String, available: Dictionary)");
        sb.AppendLine("## Emitted after the engine finishes resolving an action,");
        sb.AppendLine("## before the next [signal action_requested].");
        sb.AppendLine("signal action_resolved()");
        sb.AppendLine("## Emitted when the engine needs a player to respond to a prompt.");
        sb.AppendLine("## [param player_name] identifies which player must respond.");
        sb.AppendLine("## [param prompt_type] is the prompt class name (e.g. [code]ChoicePrompt[/code]).");
        sb.AppendLine("## [param context] contains prompt-specific fields.");
        sb.AppendLine("signal prompt_requested(player_name: String, prompt_type: String, context: Dictionary)");
        sb.AppendLine("## Emitted when the game ends. [param winner_name] is empty for a draw.");
        sb.AppendLine("signal game_over(winner_name: String)");
        sb.AppendLine("## Emitted when an unrecoverable engine error occurs.");
        sb.AppendLine("## [param message] contains the error description.");
        sb.AppendLine("signal game_error(message: String)");
        sb.AppendLine();
        sb.AppendLine("func _on_action_requested(player_name: String, available: Dictionary) -> void:");
        sb.AppendLine("    action_requested.emit(player_name, available)");
        sb.AppendLine();
        sb.AppendLine("func _on_action_resolved() -> void:");
        sb.AppendLine("    action_resolved.emit()");
        sb.AppendLine();
        sb.AppendLine("func _on_prompt_requested(player_name: String, prompt_type: String, context: Dictionary) -> void:");
        sb.AppendLine("    prompt_requested.emit(player_name, prompt_type, context)");
        sb.AppendLine();
        sb.AppendLine("func _on_game_over(winner_name: String) -> void:");
        sb.AppendLine("    game_over.emit(winner_name)");
        sb.AppendLine();
        sb.AppendLine("func _on_game_error(message: String) -> void:");
        sb.AppendLine("    game_error.emit(message)");
        sb.AppendLine();
        sb.AppendLine("## Starts the game, loading definition and card sets from the generated");
        sb.AppendLine("## [code]res://archetype/[/code] files. Call after [method register].");
        sb.AppendLine("## Pass explicit paths to override the defaults.");
        sb.AppendLine("func start(host_manifest: Dictionary = {},");
        sb.AppendLine("        definition_path: String = \"res://archetype/game_definition.json\",");
        sb.AppendLine("        card_set_paths: Array = []) -> void:");
        sb.AppendLine("    _node.StartGame(host_manifest, definition_path, card_set_paths)");
        sb.AppendLine();
        sb.AppendLine("## Submits a pass action for [param player_name].");
        sb.AppendLine("func submit_pass(player_name: String) -> void:");
        sb.AppendLine("    _node.SubmitPass(player_name)");
        sb.AppendLine();
        sb.AppendLine("## Submits a play-card action for [param player_name].");
        sb.AppendLine("## [param card_atom_id] is the atom ID from [signal action_requested].");
        sb.AppendLine("## [param cost_choices] provides any required cost selections.");
        sb.AppendLine("func submit_play_card(player_name: String, card_atom_id: int, cost_choices: Dictionary = {}) -> void:");
        sb.AppendLine("    _node.SubmitPlayCard(player_name, card_atom_id, cost_choices)");
        sb.AppendLine();
        sb.AppendLine("## Submits an activate-ability action for [param player_name].");
        sb.AppendLine("## [param source_atom_id] is the atom ID of the source card.");
        sb.AppendLine("## [param effect_name] identifies which ability to activate.");
        sb.AppendLine("## [param cost_choices] provides any required cost selections.");
        sb.AppendLine("func submit_activate_ability(player_name: String, source_atom_id: int, effect_name: String, cost_choices: Dictionary = {}) -> void:");
        sb.AppendLine("    _node.SubmitActivateAbility(player_name, source_atom_id, effect_name, cost_choices)");
        sb.AppendLine();
        sb.AppendLine("## Submits a response to a pending prompt for [param player_name].");
        sb.AppendLine("## [param response] is a dictionary of chosen values keyed by prompt field name.");
        sb.AppendLine("func submit_prompt_response(player_name: String, response: Dictionary) -> void:");
        sb.AppendLine("    _node.SubmitPromptResponse(player_name, response)");
        sb.AppendLine();
        // State query forwarding methods (D38).
        // These are callable outside an action window but return safe defaults — callers should
        // not rely on meaningful values outside the action_requested / prompt_requested window.
        sb.AppendLine("## Returns the named accumulator value for [param atom_id].");
        sb.AppendLine("## Returns 0.0 before the game starts or after it ends.");
        sb.AppendLine("func get_accumulator(atom_id: int, name: String) -> float:     return _node.GetAccumulator(atom_id, name)");
        sb.AppendLine();
        sb.AppendLine("## Returns true if the named condition is set on [param atom_id].");
        sb.AppendLine("## Returns false before the game starts or after it ends.");
        sb.AppendLine("func has_condition(atom_id: int, name: String) -> bool:        return _node.HasCondition(atom_id, name)");
        sb.AppendLine();
        sb.AppendLine("## Returns the named computed property for [param atom_id].");
        sb.AppendLine("## Returns 0.0 before the game starts or after it ends.");
        sb.AppendLine("func get_computed_property(atom_id: int, name: String) -> float: return _node.GetComputedProperty(atom_id, name)");
        sb.AppendLine();
        sb.AppendLine("## Returns the zone atom ID for the given card atom.");
        sb.AppendLine("## Returns 0 before the game starts or after it ends.");
        sb.AppendLine("func get_zone(atom_id: int) -> int:                            return _node.GetZone(atom_id)");
        sb.AppendLine();
        sb.AppendLine("## Returns the owner atom ID for the given atom.");
        sb.AppendLine("## Returns 0 before the game starts or after it ends.");
        sb.AppendLine("func get_atom_owner(atom_id: int) -> int:                      return _node.GetAtomOwner(atom_id)");
        sb.AppendLine();
        sb.AppendLine("## Returns the [ArchetypeAtomKinds] integer constant for the given atom.");
        sb.AppendLine("## Returns -1 before the game starts or after it ends.");
        sb.AppendLine("func get_kind(atom_id: int) -> int:                            return _node.GetKind(atom_id)");
        sb.AppendLine();
        sb.AppendLine("## Returns all atom IDs of the given [param kind] as an Array of ints.");
        sb.AppendLine("## Returns an empty Array before the game starts or after it ends.");
        sb.AppendLine("func get_atoms(kind: int) -> Array:                            return _node.GetAtoms(kind)");

        File.WriteAllText(Path.Combine(outputDir, "archetype_interop.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  AtomKind constants file (D39)
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>archetype_atom_kinds.gd</c> to <paramref name="outputDir"/> (D39).
    /// <para>
    /// Contains integer constants for each <see cref="AtomKind"/> value so GDScript
    /// can pass kinds to <c>ArchetypeInterop.get_atoms</c> and read the result of
    /// <c>ArchetypeInterop.get_kind</c> without hard-coding magic numbers.
    /// The values are the underlying <c>int</c> ordinals of <see cref="AtomKind"/>
    /// in declaration order: Card=0, Zone=1, Player=2, Session=3.
    /// </para>
    /// </summary>
    public static void EmitAtomKindConstants(string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_atom_kinds.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("## Integer constants for AtomKind values.");
        sb.AppendLine("## Use with [method ArchetypeInterop.get_atoms] and [method ArchetypeInterop.get_kind].");
        sb.AppendLine("class_name ArchetypeAtomKinds");
        sb.AppendLine();
        // Values must match AtomKind enum declaration order in Archetype.Core (D39 cross-language contract).
        sb.AppendLine($"const CARD    = {(int)AtomKind.Card}");
        sb.AppendLine($"const ZONE    = {(int)AtomKind.Zone}");
        sb.AppendLine($"const PLAYER  = {(int)AtomKind.Player}");
        sb.AppendLine($"const SESSION = {(int)AtomKind.Session}");

        File.WriteAllText(Path.Combine(outputDir, "archetype_atom_kinds.gd"), sb.ToString());
    }

    private static void CollectFromBlock(EffectBlockDef block, HashSet<string> collected)
    {
        foreach (var step in block.Steps)
            collected.Add(step.KeywordName);
    }

    /// <summary>
    /// Converts a kebab-case keyword name to SCREAMING_SNAKE_CASE.
    /// <example><c>take-damage</c> → <c>TAKE_DAMAGE</c></example>
    /// </summary>
    internal static string ToScreamingSnakeCase(string name) =>
        name.Replace('-', '_').ToUpperInvariant();

    /// <summary>
    /// Converts a kebab-case or snake_case keyword name to PascalCase for use
    /// in C# signal handler names.
    /// <example><c>take-damage</c> → <c>TakeDamage</c></example>
    /// </summary>
    internal static string ToPascalCase(string name)
    {
        var parts = name.Split('-', '_');
        return string.Concat(parts.Select(p =>
            p.Length == 0 ? string.Empty : char.ToUpperInvariant(p[0]) + p[1..]));
    }

    /// <summary>Returns a plain-English description of a parameter for GDScript doc comments.</summary>
    private static string GdScriptParamDescription(string paramName, TypeName type) => type switch
    {
        TypeName.Card or TypeName.Atom          => $"atom ID of the {paramName}",
        TypeName.Zone                           => $"atom ID of the {paramName} zone",
        TypeName.Player                         => $"atom ID of the {paramName} player",
        TypeName.Number                         => $"numeric value",
        TypeName.Boolean                        => $"boolean flag",
        TypeName.PropertyName                   => $"property name string",
        TypeName.CardDefinitionName             => $"card definition name",
        TypeName.ZoneDefinitionName             => $"zone definition name",
        _                                       => $"value",
    };

    /// <summary>Maps an engine <see cref="TypeName"/> to a GDScript type annotation.</summary>
    internal static string MapToGdScriptType(TypeName type) => type switch
    {
        TypeName.Number                                           => "float",
        TypeName.Boolean                                          => "bool",
        TypeName.Atom or TypeName.Card or TypeName.Zone
            or TypeName.Player or TypeName.Session
            or TypeName.ContributionId                            => "int",
        TypeName.ConditionName or TypeName.PropertyName           => "String",
        TypeName.CardDefinitionName or TypeName.ZoneDefinitionName => "String",
        _                                                         => "Variant",
    };

    /// <summary>
    /// Maps an engine <see cref="TypeName"/> to the C# type used in the generated
    /// <c>ArchetypeNode.cs</c> signal handler signature.
    /// </summary>
    internal static string MapToCSharpType(TypeName type) => type switch
    {
        TypeName.Number                          => "double",
        TypeName.Boolean                         => "bool",
        TypeName.Atom or TypeName.Card
            or TypeName.Zone or TypeName.Player
            or TypeName.Session
            or TypeName.ContributionId           => "long",
        _                                        => "string",
    };

    /// <summary>
    /// Returns a C# cast expression for extracting a <see cref="TypeName"/>-typed
    /// value from the <c>BoundArgs</c> dictionary in <c>EmitDerivedSignals</c>.
    /// </summary>
    private static string GetEventArgCast(TypeName type) => type switch
    {
        TypeName.Number  => "(double)",
        TypeName.Boolean => "(bool)",
        TypeName.Atom or TypeName.Card or TypeName.Zone
            or TypeName.Player or TypeName.Session
            or TypeName.ContributionId => "(long)(AtomId)",
        _ => "(string)",
    };
}
