using System.Text;
using Archetype.Core;

namespace Archetype.Build;

/// <summary>
/// Generates GDScript interop files from a <see cref="GameDefinition"/> (D32, D33).
/// <para>
/// Files produced:
/// <list type="bullet">
///   <item><c>archetype_keywords.gd</c> — SCREAMING_SNAKE_CASE string constants for every registered keyword name.</item>
///   <item><c>game_events.gd</c> — GDScript signal declarations derived from keyword event log contributions.</item>
///   <item><c>ArchetypeNode.cs</c> — generated C# partial class bridging <c>GameSession</c> to GDScript (D33).</item>
///   <item><c>archetype_signals.gd</c> — per-game signal name constants in SCREAMING_SNAKE_CASE (D33).</item>
///   <item><c>archetype_interop.gd</c> — static autoload wrapper over <c>ArchetypeNode</c> (D33).</item>
/// </list>
/// </para>
/// </summary>
public static class GodotEmitter
{
    // -----------------------------------------------------------------------
    //  Keyword constants file
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>archetype_keywords.gd</c> to <paramref name="outputDir"/>.
    /// Contains one SCREAMING_SNAKE_CASE string constant per registered keyword name.
    /// </summary>
    public static void EmitKeywordConstants(GameDefinition definition, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_keywords.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("class_name ArchetypeKeywords");
        sb.AppendLine();

        foreach (var name in definition.Keywords.Keys.OrderBy(k => k))
        {
            var constName = ToScreamingSnakeCase(name);
            sb.AppendLine($"const {constName} = \"{name}\"");
        }

        File.WriteAllText(Path.Combine(outputDir, "archetype_keywords.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  Signal definitions file
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>game_events.gd</c> to <paramref name="outputDir"/>.
    /// <para>
    /// Signal derivation rules (D32 / D30):
    /// <list type="bullet">
    ///   <item>A keyword produces a signal if it is directly referenced as an
    ///         <c>EffectBlockStep</c> in any card's primary effect, additional
    ///         effect bodies, or cost bodies.</item>
    ///   <item>Built-in primitives are suppressed by default.</item>
    ///   <item>Keywords in <paramref name="noSignalKeywords"/> are excluded.</item>
    /// </list>
    /// </para>
    /// </summary>
    public static void EmitSignals(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var included = DeriveSignalSet(definition, noSignalKeywords);

        var sb = new StringBuilder();
        sb.AppendLine("# game_events.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("class_name GameEvents");
        sb.AppendLine();

        if (included.Count == 0)
        {
            sb.AppendLine("# No game-creator keyword signals derived from card definitions.");
        }
        else
        {
            foreach (var name in included)
            {
                if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
                var signalName = "on_" + name.Replace('-', '_');
                var paramList = string.Join(", ", kw.Parameters.Select(p =>
                    $"{p.Name}: {MapToGdScriptType(p.Type)}"));
                sb.AppendLine($"signal {signalName}({paramList})");
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "game_events.gd"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  ArchetypeNode.cs — C# bridge class (D33)
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>ArchetypeNode.cs</c> to <paramref name="outputDir"/> (D33).
    /// <para>
    /// The generated class is a Godot <c>Node</c> partial that wraps
    /// <c>GameSession</c>, implements <c>IPlayerStrategy</c> internally for
    /// every player, and bridges the async action loop to GDScript via
    /// <c>TaskCompletionSource</c>-based suspension.  All Godot coupling is
    /// confined to the generated string — the <c>Archetype.*</c> assemblies
    /// gain no Godot reference.
    /// </para>
    /// </summary>
    public static void EmitArchetypeNode(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var signalSet = DeriveSignalSet(definition, noSignalKeywords);
        var playerNames = definition.PlayerDefinitions.Keys.OrderBy(n => n).ToList();

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// ArchetypeNode.cs — generated by Archetype.Build; do not edit");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Godot;");
        sb.AppendLine("using Archetype.Core;");
        sb.AppendLine("using Archetype.Engine;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated Godot node that hosts a <c>GameSession</c> and bridges the async");
        sb.AppendLine("/// action loop to GDScript via signal/method pairs (D33).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[GlobalClass]");
        sb.AppendLine("public partial class ArchetypeNode : Node");
        sb.AppendLine("{");

        // --- Signal declarations ---
        sb.AppendLine("    // --- Engine lifecycle signals ---");
        sb.AppendLine("    [Signal] public delegate void ActionRequestedEventHandler(string playerName, Godot.Collections.Dictionary availableActions);");
        sb.AppendLine("    [Signal] public delegate void ActionResolvedEventHandler();");
        sb.AppendLine("    [Signal] public delegate void PromptRequestedEventHandler(string playerName, string promptType, Godot.Collections.Dictionary context);");
        sb.AppendLine("    [Signal] public delegate void GameOverEventHandler(string winnerName);");
        sb.AppendLine("    [Signal] public delegate void GameErrorEventHandler(string message);");
        sb.AppendLine();

        if (signalSet.Count > 0)
        {
            sb.AppendLine("    // --- Derived keyword signals ---");
            foreach (var name in signalSet)
            {
                if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
                var handlerName = "On" + ToPascalCase(name) + "EventHandler";
                var paramList = string.Join(", ", kw.Parameters.Select(p =>
                    $"{MapToCSharpType(p.Type)} {p.Name}"));
                sb.AppendLine($"    [Signal] public delegate void {handlerName}({paramList});");
            }
            sb.AppendLine();
        }

        // --- Session fields ---
        sb.AppendLine("    // --- Session state ---");
        sb.AppendLine("    private Task? _runTask;");
        sb.AppendLine("    private CancellationTokenSource? _cts;");
        sb.AppendLine();

        // One TCS pair per player for action + prompt suspension.
        // We use runtime dictionaries keyed by player name so the same node
        // handles games with any number of players.
        sb.AppendLine("    // Per-player suspension: one TCS per outstanding SelectAction / RespondToPrompt call.");
        sb.AppendLine("    private readonly Dictionary<string, TaskCompletionSource<PlayerAction?>> _pendingActions = new();");
        sb.AppendLine("    private readonly Dictionary<string, TaskCompletionSource<PromptResponse>> _pendingPrompts = new();");
        sb.AppendLine();

        // --- StartGame ---
        sb.AppendLine("    // --- Session startup ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Called from GDScript to start the game.  Builds the session, wires");
        sb.AppendLine("    /// per-player strategies, and launches the async loop as fire-and-forget.");
        sb.AppendLine("    /// <paramref name=\"hostManifestData\"/> is forwarded as-is to the engine;");
        sb.AppendLine("    /// pass an empty <c>Dictionary</c> if no session-specific cards are needed.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void StartGame(Godot.Collections.Dictionary hostManifestData, GameDefinition definition)");
        sb.AppendLine("    {");
        sb.AppendLine("        _cts = new CancellationTokenSource();");
        sb.AppendLine();
        sb.AppendLine("        var builder = GameSession.Create(definition)");
        sb.AppendLine("            .WithRandomSource(new Archetype.Engine.SeededRandom(GD.Randi()));");
        sb.AppendLine();

        // Register one inner strategy per declared player
        foreach (var playerName in playerNames)
        {
            sb.AppendLine($"        builder = builder.WithPlayerStrategy(\"{playerName}\", new InnerStrategy(\"{playerName}\", this));");
        }

        sb.AppendLine();
        sb.AppendLine("        var session = builder.Build();");
        sb.AppendLine("        _runTask = RunLoopAsync(session, _cts.Token);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- RunLoopAsync ---
        sb.AppendLine("    private async Task RunLoopAsync(GameSession session, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = await session.RunAsync(ct);");
        sb.AppendLine("            // winnerName is empty string for a draw (D33 spec).");
        sb.AppendLine("            EmitSignal(SignalName.GameOver, result.Winner ?? string.Empty);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.OperationCanceledException)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Normal shutdown: node exited tree while game was running.");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            GD.PrintErr(\"[ArchetypeNode] engine error: \", ex.Message);");
        sb.AppendLine("            EmitSignal(SignalName.GameError, ex.Message);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- _ExitTree ---
        sb.AppendLine("    /// <summary>Cancels the game loop when the node leaves the scene tree.</summary>");
        sb.AppendLine("    public override void _ExitTree()");
        sb.AppendLine("    {");
        sb.AppendLine("        _cts?.Cancel();");
        sb.AppendLine("        _cts?.Dispose();");
        sb.AppendLine("        _cts = null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- Action submission methods ---
        sb.AppendLine("    // --- GDScript-callable action submission methods ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits a play-card action for the named player.</summary>");
        sb.AppendLine("    public void SubmitPlayCard(string playerName, long cardAtomId, Godot.Collections.Dictionary costChoices)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        var choices = DictionaryToStringObject(costChoices);");
        sb.AppendLine("        tcs.TrySetResult(new PlayCard(new AtomId((int)cardAtomId), choices));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits an activate-ability action for the named player.</summary>");
        sb.AppendLine("    public void SubmitActivateAbility(string playerName, long sourceAtomId, string effectName, Godot.Collections.Dictionary costChoices)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        var choices = DictionaryToStringObject(costChoices);");
        sb.AppendLine("        tcs.TrySetResult(new ActivateAbility(new AtomId((int)sourceAtomId), effectName, choices));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits a pass action for the named player.</summary>");
        sb.AppendLine("    public void SubmitPass(string playerName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        tcs.TrySetResult(new Pass());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Submits a prompt response for the named player.</summary>");
        sb.AppendLine("    public void SubmitPromptResponse(string playerName, Godot.Collections.Dictionary response)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_pendingPrompts.TryGetValue(playerName, out var tcs)) return;");
        sb.AppendLine("        var chosen = new System.Collections.Generic.List<object>();");
        sb.AppendLine("        foreach (var key in response.Keys)");
        sb.AppendLine("            chosen.Add(response[key]);");
        sb.AppendLine("        tcs.TrySetResult(new ChoiceResponse(chosen));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- EmitDerivedSignals ---
        sb.AppendLine("    // --- Post-action signal emission ---");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Iterates <paramref name=\"events\"/> (depth-first) and emits a hardcoded");
        sb.AppendLine("    /// GDScript signal for every event whose keyword name is in the derived set.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private void EmitDerivedSignals(System.Collections.Generic.IReadOnlyList<GameEvent> events)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var root in events)");
        sb.AppendLine("        foreach (var ev in root.SelfAndDescendants())");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (ev.KeywordName)");
        sb.AppendLine("            {");

        foreach (var name in signalSet)
        {
            if (!definition.Keywords.TryGetValue(name, out var kw)) continue;
            var signalConstant = "SignalName.On" + ToPascalCase(name);
            sb.AppendLine($"                case \"{name}\":");
            sb.AppendLine($"                    EmitSignal({signalConstant}");

            foreach (var p in kw.Parameters)
            {
                var cast = GetEventArgCast(p.Type);
                sb.AppendLine($"                        , {cast}(ev.BoundArgs[\"{p.Name}\"])");
            }

            sb.AppendLine("                    );");
            sb.AppendLine("                    break;");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- DictionaryToStringObject helper ---
        sb.AppendLine("    private static System.Collections.Generic.Dictionary<string, object> DictionaryToStringObject(");
        sb.AppendLine("        Godot.Collections.Dictionary dict)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new System.Collections.Generic.Dictionary<string, object>(StringComparer.Ordinal);");
        sb.AppendLine("        foreach (var key in dict.Keys)");
        sb.AppendLine("            result[key.ToString()!] = dict[key];");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- InnerStrategy nested class ---
        sb.AppendLine("    // --- InnerStrategy — per-player IPlayerStrategy implementation ---");
        sb.AppendLine();
        sb.AppendLine("    private sealed class InnerStrategy : IPlayerStrategy");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly string _playerName;");
        sb.AppendLine("        private readonly ArchetypeNode _node;");
        sb.AppendLine();
        sb.AppendLine("        public InnerStrategy(string playerName, ArchetypeNode node)");
        sb.AppendLine("        {");
        sb.AppendLine("            _playerName = playerName;");
        sb.AppendLine("            _node = node;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task<PlayerAction?> SelectActionAsync(");
        sb.AppendLine("            AvailableActions available,");
        sb.AppendLine("            GameStateView state,");
        sb.AppendLine("            CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Emit derived signals for the just-completed action before opening");
        sb.AppendLine("            // the next decision window.  LastActionEvents is populated by the");
        sb.AppendLine("            // engine after all blocks, SBRs, and triggers resolve (D30).");
        sb.AppendLine("            _node.EmitDerivedSignals(state.LastActionEvents);");
        sb.AppendLine("            _node.EmitSignal(SignalName.ActionResolved);");
        sb.AppendLine();
        sb.AppendLine("            // Serialise available actions to a plain Dictionary for GDScript.");
        sb.AppendLine("            var availableDict = SerialiseAvailableActions(available);");
        sb.AppendLine("            var tcs = new TaskCompletionSource<PlayerAction?>(");
        sb.AppendLine("                TaskCreationOptions.RunContinuationsAsynchronously);");
        sb.AppendLine("            _node._pendingActions[_playerName] = tcs;");
        sb.AppendLine("            _node.EmitSignal(SignalName.ActionRequested, _playerName, availableDict);");
        sb.AppendLine();
        sb.AppendLine("            using var reg = ct.Register(() => tcs.TrySetCanceled());");
        sb.AppendLine("            return await tcs.Task;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task<PromptResponse> RespondToPromptAsync(");
        sb.AppendLine("            PromptContext context,");
        sb.AppendLine("            GameStateView state,");
        sb.AppendLine("            CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            var promptType = context.GetType().Name;");
        sb.AppendLine("            var contextDict = new Godot.Collections.Dictionary();");
        sb.AppendLine("            var tcs = new TaskCompletionSource<PromptResponse>(");
        sb.AppendLine("                TaskCreationOptions.RunContinuationsAsynchronously);");
        sb.AppendLine("            _node._pendingPrompts[_playerName] = tcs;");
        sb.AppendLine("            _node.EmitSignal(SignalName.PromptRequested, _playerName, promptType, contextDict);");
        sb.AppendLine();
        sb.AppendLine("            using var reg = ct.Register(() => tcs.TrySetCanceled());");
        sb.AppendLine("            return await tcs.Task;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static Godot.Collections.Dictionary SerialiseAvailableActions(AvailableActions available)");
        sb.AppendLine("        {");
        sb.AppendLine("            var dict = new Godot.Collections.Dictionary();");
        sb.AppendLine("            var cards = new Godot.Collections.Array();");
        sb.AppendLine("            foreach (var opt in available.PlayableCards)");
        sb.AppendLine("                cards.Add((long)opt.Card);");
        sb.AppendLine("            dict[\"playable_cards\"] = cards;");
        sb.AppendLine("            var abilities = new Godot.Collections.Array();");
        sb.AppendLine("            foreach (var opt in available.ActivatableAbilities)");
        sb.AppendLine("            {");
        sb.AppendLine("                var entry = new Godot.Collections.Dictionary();");
        sb.AppendLine("                entry[\"source\"] = (long)opt.Source;");
        sb.AppendLine("                entry[\"effect_name\"] = opt.EffectName;");
        sb.AppendLine("                abilities.Add(entry);");
        sb.AppendLine("            }");
        sb.AppendLine("            dict[\"activatable_abilities\"] = abilities;");
        sb.AppendLine("            dict[\"can_pass\"] = available.CanPass;");
        sb.AppendLine("            return dict;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("}");

        File.WriteAllText(Path.Combine(outputDir, "ArchetypeNode.cs"), sb.ToString());
    }

    // -----------------------------------------------------------------------
    //  GDScript interop files (D33)
    // -----------------------------------------------------------------------

    /// <summary>
    /// Emits <c>archetype_signals.gd</c> and <c>archetype_interop.gd</c> to
    /// <paramref name="outputDir"/> (D33).
    /// <para>
    /// <c>archetype_signals.gd</c> contains one SCREAMING_SNAKE_CASE constant
    /// per derived signal name, parallel to <c>archetype_keywords.gd</c>.
    /// </para>
    /// <para>
    /// <c>archetype_interop.gd</c> is a static autoload that re-emits
    /// <c>ArchetypeNode</c> signals so GDScript scripts can connect to a single
    /// stable node rather than to a scene-position-dependent node reference.
    /// Its content does not vary per game.
    /// </para>
    /// </summary>
    public static void EmitInteropScripts(
        GameDefinition definition,
        string outputDir,
        IEnumerable<string>? noSignalKeywords = null)
    {
        var signalSet = DeriveSignalSet(definition, noSignalKeywords);
        EmitSignalConstants(signalSet, outputDir);
        EmitInteropAutoload(outputDir);
    }

    // -----------------------------------------------------------------------
    //  Private helpers
    // -----------------------------------------------------------------------

    /// <summary>
    /// Derives the ordered set of keyword names for which GDScript signals
    /// should be generated.  Shared by <see cref="EmitSignals"/>,
    /// <see cref="EmitArchetypeNode"/>, and <see cref="EmitInteropScripts"/>.
    /// <para>
    /// Derivation rules (D30 / D32):
    /// keywords referenced directly in card effect steps, excluding built-in
    /// primitives and any name in <paramref name="noSignalKeywords"/>.
    /// </para>
    /// </summary>
    private static List<string> DeriveSignalSet(
        GameDefinition definition,
        IEnumerable<string>? noSignalKeywords)
    {
        var suppressed = noSignalKeywords?.ToHashSet() ?? [];
        var builtInNames = BuiltInKeywords.All.Select(k => k.Name).ToHashSet();

        // Collect keyword names directly referenced in card effect blocks.
        var referenced = new HashSet<string>();
        foreach (var card in definition.CardDefinitions.Values)
        {
            CollectFromBlock(card.PrimaryEffect, referenced);
            foreach (var extra in card.AdditionalEffects)
                CollectFromBlock(extra.Body, referenced);
            foreach (var cost in card.Cost ?? [])
                CollectFromBlock(cost.Body, referenced);
            // D32: also scan static effect blocks — both the state-contribution
            // block and the trigger's fired block count as referenced.
            foreach (var se in card.StaticEffects)
            {
                if (se.StateContributionBlock is not null)
                    CollectFromBlock(se.StateContributionBlock, referenced);
                if (se.Trigger is not null)
                    CollectFromBlock(se.Trigger.FiredBlock, referenced);
            }
        }

        // Apply derivation rules: exclude built-ins and opted-out keywords.
        return referenced
            .Where(name => !builtInNames.Contains(name))
            .Where(name => !suppressed.Contains(name))
            .OrderBy(name => name)
            .ToList();
    }

    /// <summary>Emits <c>archetype_signals.gd</c> from a pre-computed signal set.</summary>
    private static void EmitSignalConstants(List<string> signalSet, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# archetype_signals.gd — generated by Archetype.Build; do not edit");
        sb.AppendLine("class_name ArchetypeSignals");
        sb.AppendLine();

        if (signalSet.Count == 0)
        {
            sb.AppendLine("# No game-creator keyword signals derived from card definitions.");
        }
        else
        {
            foreach (var name in signalSet)
            {
                var signalName = "on_" + name.Replace('-', '_');
                var constName = ToScreamingSnakeCase(signalName);
                sb.AppendLine($"const {constName} = \"{signalName}\"");
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "archetype_signals.gd"), sb.ToString());
    }

    /// <summary>
    /// Emits the game-agnostic <c>archetype_interop.gd</c> autoload.
    /// Content is fixed — it does not reference any derived signals.
    /// </summary>
    private static void EmitInteropAutoload(string outputDir)
    {
        // The content is verbatim from D33.  It is identical for every game.
        const string content =
            """
            # archetype_interop.gd — generated by Archetype.Build; do not edit
            # Add to Project Settings > Autoload as "ArchetypeInterop"
            extends Node

            var _node: ArchetypeNode

            func register(node: ArchetypeNode) -> void:
                _node = node
                _node.action_requested.connect(_on_action_requested)
                _node.action_resolved.connect(_on_action_resolved)
                _node.game_over.connect(_on_game_over)

            signal action_requested(player_name: String, available: Dictionary)
            signal action_resolved()
            signal game_over(winner_name: String)

            func _on_action_requested(player_name: String, available: Dictionary) -> void:
                action_requested.emit(player_name, available)

            func _on_action_resolved() -> void:
                action_resolved.emit()

            func _on_game_over(winner_name: String) -> void:
                game_over.emit(winner_name)

            func submit_pass(player_name: String) -> void:
                _node.SubmitPass(player_name)

            func submit_play_card(player_name: String, card_atom_id: int, cost_choices: Dictionary = {}) -> void:
                _node.SubmitPlayCard(player_name, card_atom_id, cost_choices)

            func submit_activate_ability(player_name: String, source_atom_id: int, effect_name: String, cost_choices: Dictionary = {}) -> void:
                _node.SubmitActivateAbility(player_name, source_atom_id, effect_name, cost_choices)

            func submit_prompt_response(player_name: String, response: Dictionary) -> void:
                _node.SubmitPromptResponse(player_name, response)
            """;

        File.WriteAllText(Path.Combine(outputDir, "archetype_interop.gd"), content);
    }

    private static void CollectFromBlock(EffectBlockDef block, HashSet<string> collected)
    {
        foreach (var step in block.Steps)
            collected.Add(step.KeywordName);
    }

    /// <summary>
    /// Converts a kebab-case keyword name to SCREAMING_SNAKE_CASE.
    /// <example><c>take-damage</c> → <c>TAKE_DAMAGE</c></example>
    /// </summary>
    internal static string ToScreamingSnakeCase(string name) =>
        name.Replace('-', '_').ToUpperInvariant();

    /// <summary>
    /// Converts a kebab-case or snake_case keyword name to PascalCase for use
    /// in C# signal handler names.
    /// <example><c>take-damage</c> → <c>TakeDamage</c></example>
    /// </summary>
    internal static string ToPascalCase(string name)
    {
        var parts = name.Split('-', '_');
        return string.Concat(parts.Select(p =>
            p.Length == 0 ? string.Empty : char.ToUpperInvariant(p[0]) + p[1..]));
    }

    /// <summary>Maps an engine <see cref="TypeName"/> to a GDScript type annotation.</summary>
    internal static string MapToGdScriptType(TypeName type) => type switch
    {
        TypeName.Number                                           => "float",
        TypeName.Boolean                                          => "bool",
        TypeName.Atom or TypeName.Card or TypeName.Zone
            or TypeName.Player or TypeName.Session
            or TypeName.ContributionId                            => "int",
        TypeName.ConditionName or TypeName.PropertyName           => "String",
        TypeName.CardDefinitionName or TypeName.ZoneDefinitionName => "String",
        _                                                         => "Variant",
    };

    /// <summary>
    /// Maps an engine <see cref="TypeName"/> to the C# type used in the generated
    /// <c>ArchetypeNode.cs</c> signal handler signature.
    /// </summary>
    internal static string MapToCSharpType(TypeName type) => type switch
    {
        TypeName.Number                          => "double",
        TypeName.Boolean                         => "bool",
        TypeName.Atom or TypeName.Card
            or TypeName.Zone or TypeName.Player
            or TypeName.Session
            or TypeName.ContributionId           => "long",
        _                                        => "string",
    };

    /// <summary>
    /// Returns a C# cast expression for extracting a <see cref="TypeName"/>-typed
    /// value from the <c>BoundArgs</c> dictionary in <c>EmitDerivedSignals</c>.
    /// </summary>
    private static string GetEventArgCast(TypeName type) => type switch
    {
        TypeName.Number  => "(double)",
        TypeName.Boolean => "(bool)",
        TypeName.Atom or TypeName.Card or TypeName.Zone
            or TypeName.Player or TypeName.Session
            or TypeName.ContributionId => "(long)(AtomId)",
        _ => "(string)",
    };
}
