using Archetype.Core;
using Archetype.Build;
using ABuild = Archetype.Build;

namespace Archetype.Tests.GodotEmitter;

/// <summary>
/// Tests for <see cref="GodotEmitter.EmitAtomViews"/> (D40).
/// </summary>
public class AtomViewEmitterTests : IDisposable
{
    private readonly string _tempDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());

    public AtomViewEmitterTests()
    {
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, recursive: true);
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    private static readonly IReadOnlyDictionary<string, object> NoProps =
        new Dictionary<string, object>();

    private static GameDefinition EmptyDefinition() =>
        new GameDefinitionBuilder()
            .WithId("test")
            .WithInitManifest(InitManifest.Empty)
            .Build();

    private static GameDefinition DefinitionWithCard(params StateFieldDecl[] decls)
    {
        var card = new CardDefinition(
            Name: "TestCard",
            StaticProperties: NoProps,
            PrimaryEffect: EffectBlockDef.Empty,
            AdditionalEffects: [],
            StaticEffects: [],
            StateMapDeclarations: decls.ToList());
        return new GameDefinitionBuilder()
            .WithId("test")
            .WithInitManifest(InitManifest.Empty)
            .AddCard(card)
            .Build();
    }

    private static GameDefinition DefinitionWithZone(params StateFieldDecl[] decls)
    {
        return new GameDefinitionBuilder()
            .WithId("test")
            .WithInitManifest(InitManifest.Empty)
            .AddZone("test-zone", NoProps, decls.ToList())
            .Build();
    }

    private static GameDefinition DefinitionWithSession(params StateFieldDecl[] decls)
    {
        return new GameDefinitionBuilder()
            .WithId("test")
            .WithInitManifest(InitManifest.Empty)
            .WithSessionStateMap(decls.ToList())
            .Build();
    }

    private string ReadFile(string name) =>
        File.ReadAllText(Path.Combine(_tempDir, name));

    /// <summary>
    /// Writes a base interop file so AppendInteropFactoryMethods has something to append to.
    /// </summary>
    private void WriteBaseInteropFile()
    {
        // Simulate EmitInteropScripts having already run by creating a minimal base file.
        File.WriteAllText(
            Path.Combine(_tempDir, "archetype_interop.gd"),
            "# archetype_interop.gd — generated by Archetype.Build; do not edit\nextends Node\n");
    }

    // -----------------------------------------------------------------------
    //  Field getter / predicate generation
    // -----------------------------------------------------------------------

    [Fact]
    public void EmitAtomViews_NumberField_GeneratesGetterMethod()
    {
        var def = DefinitionWithCard(new StateFieldDecl("health", StateFieldType.Number));
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("card_atom.gd");
        Assert.Contains("func get_health() -> float:", content);
        Assert.Contains("ArchetypeInterop.get_accumulator(_atom_id, \"health\")", content);
    }

    [Fact]
    public void EmitAtomViews_BoolField_GeneratesPredicateMethod()
    {
        var def = DefinitionWithCard(new StateFieldDecl("poisoned", StateFieldType.Bool));
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("card_atom.gd");
        Assert.Contains("func has_poisoned() -> bool:", content);
        Assert.Contains("ArchetypeInterop.has_condition(_atom_id, \"poisoned\")", content);
    }

    // -----------------------------------------------------------------------
    //  Structural getters
    // -----------------------------------------------------------------------

    [Fact]
    public void EmitAtomViews_CardAtom_StructuralGetters_AlwaysPresent()
    {
        var def = EmptyDefinition();
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("card_atom.gd");
        Assert.Contains("func get_atom_id() -> int:", content);
        Assert.Contains("func get_zone_id() -> int:", content);
        Assert.Contains("func get_owner_id() -> int:", content);
        Assert.Contains("ArchetypeInterop.get_zone(_atom_id)", content);
        Assert.Contains("ArchetypeInterop.get_atom_owner(_atom_id)", content);
    }

    [Fact]
    public void EmitAtomViews_ZoneAtom_OwnerId_Present_ZoneId_Absent()
    {
        var def = EmptyDefinition();
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("zone_atom.gd");
        Assert.Contains("func get_atom_id() -> int:", content);
        Assert.Contains("func get_owner_id() -> int:", content);
        // Zone atoms don't have zone_id — they ARE the zone.
        Assert.DoesNotContain("func get_zone_id() -> int:", content);
    }

    [Fact]
    public void EmitAtomViews_SessionAtom_NoOwnerId_NoZoneId()
    {
        var def = EmptyDefinition();
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("session_atom.gd");
        Assert.Contains("func get_atom_id() -> int:", content);
        Assert.DoesNotContain("func get_owner_id() -> int:", content);
        Assert.DoesNotContain("func get_zone_id() -> int:", content);
    }

    // -----------------------------------------------------------------------
    //  Union across definitions
    // -----------------------------------------------------------------------

    [Fact]
    public void EmitAtomViews_UnionAcrossDefinitions_DeduplicatesMatchingFields()
    {
        // Two card definitions both declare "health" as Number → appears once.
        var card1 = new CardDefinition(
            Name: "CardA",
            StaticProperties: NoProps,
            PrimaryEffect: EffectBlockDef.Empty,
            AdditionalEffects: [],
            StaticEffects: [],
            StateMapDeclarations: [new StateFieldDecl("health", StateFieldType.Number)]);
        var card2 = new CardDefinition(
            Name: "CardB",
            StaticProperties: NoProps,
            PrimaryEffect: EffectBlockDef.Empty,
            AdditionalEffects: [],
            StaticEffects: [],
            StateMapDeclarations: [new StateFieldDecl("health", StateFieldType.Number)]);

        var def = new GameDefinitionBuilder()
            .WithId("test")
            .WithInitManifest(InitManifest.Empty)
            .AddCard(card1)
            .AddCard(card2)
            .Build();

        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("card_atom.gd");
        // "get_health" should appear exactly once (the method definition).
        var count = CountOccurrences(content, "func get_health() -> float:");
        Assert.Equal(1, count);
    }

    // -----------------------------------------------------------------------
    //  Interop factory methods
    // -----------------------------------------------------------------------

    [Fact]
    public void EmitAtomViews_FactoryMethods_AppendedToInterop()
    {
        var def = EmptyDefinition();
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("archetype_interop.gd");
        Assert.Contains("func get_card(atom_id: int) -> CardAtom:", content);
        Assert.Contains("func get_zone_atom(atom_id: int) -> ZoneAtom:", content);
        Assert.Contains("func get_player(atom_id: int) -> PlayerAtom:", content);
        Assert.Contains("func get_session() -> SessionAtom:", content);
    }

    [Fact]
    public void EmitAtomViews_GetSession_SingletonPattern_InEmittedCode()
    {
        var def = EmptyDefinition();
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("archetype_interop.gd");
        // Singleton guard and cache field.
        Assert.Contains("var _session_atom: SessionAtom = null", content);
        Assert.Contains("if _session_atom == null:", content);
        Assert.Contains("ArchetypeAtomKinds.SESSION", content);
    }

    // -----------------------------------------------------------------------
    //  Empty declarations → structural getters only
    // -----------------------------------------------------------------------

    [Fact]
    public void EmitAtomViews_EmptyDeclarations_OnlyStructuralGetters()
    {
        var def = EmptyDefinition();
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("card_atom.gd");
        // Per-field getters must not be generated when there are no state field declarations.
        // (get_accumulators / get_active_conditions are structural discovery methods — always present.)
        Assert.DoesNotContain("ArchetypeInterop.get_accumulator(_atom_id,", content);
        Assert.DoesNotContain("ArchetypeInterop.has_condition(_atom_id,", content);
        // Structural getters must still be there.
        Assert.Contains("func get_atom_id() -> int:", content);
        Assert.Contains("func get_zone_id() -> int:", content);
        Assert.Contains("func get_owner_id() -> int:", content);
    }

    // -----------------------------------------------------------------------
    //  Snake case conversion of hyphenated names
    // -----------------------------------------------------------------------

    [Fact]
    public void EmitAtomViews_FieldNameToSnakeCase_HyphenatedName()
    {
        var def = DefinitionWithCard(
            new StateFieldDecl("is-shielded", StateFieldType.Bool));
        WriteBaseInteropFile();
        ABuild.GodotEmitter.EmitAtomViews(def, _tempDir);

        var content = ReadFile("card_atom.gd");
        // Hyphens → underscores in method name.
        Assert.Contains("func has_is_shielded() -> bool:", content);
        // Original name used in the string arg.
        Assert.Contains("\"is-shielded\"", content);
    }

    // -----------------------------------------------------------------------
    //  Helper
    // -----------------------------------------------------------------------

    private static int CountOccurrences(string text, string pattern)
    {
        int count = 0;
        int index = 0;
        while ((index = text.IndexOf(pattern, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += pattern.Length;
        }
        return count;
    }
}
