<Project>
  <PropertyGroup>
    <Authors>Bjørnar Prytz</Authors>
    <RepositoryUrl>https://github.com/bjornarprytz/Archetype</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/bjornarprytz/Archetype</PackageProjectUrl>
    <PackageTags>archetype;card-game;game-engine;godot</PackageTags>
    <IsPackable>true</IsPackable>
    <Version>0.5.0-alpha</Version>
  </PropertyGroup>
</Project>
